const TYPE = {
  GET_NEWS: "GET-NEWS",
  FAVES_NEWS: "FAVES-NEWS",
  UPDATE_SELECT: "UPDATE-SELECT",
  ACTIVE_BUTTON: "ACTIVE-BUTTON",
  UPDATE_PAGE_BY_FRAMEWORD: "ACTIVE-BUTTON",
};

export default TYPE;
