const TYPE = {
  GET_NEWS: 'GET-NEWS',
  ADD_MORE_NEWS: 'ADD-MORE-NEWS',
  FAVES_NEWS: 'FAVES-NEWS',
  UPDATE_SELECT: 'UPDATE-SELECT',
  ACTIVE_BUTTON: 'ACTIVE-BUTTON',
  UPDATE_PAGE_BY_FRAMEWORD: 'UPDATE-PAGE',
  UPDATE_NUM_ITEM: 'UPDATE-NUM-ITEM',
};

export default TYPE;
